name: "PSEG Long Island Automation"
url: "https://github.com/daswass/ha-psegli"
maintainer: "Eric Wasserman"
description: "Automated PSEG Long Island login and energy data retrieval"
version: "2.2.0"
homeassistant: "2024.8.0"
